apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "grafana-exporter.fullname" . }}
  labels:
    app: {{ template "grafana-exporter.name" . }}
    chart: {{ template "grafana-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    operator: {{ template "grafana-exporter.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "grafana-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "grafana-exporter.name" . }}
        release: {{ .Release.Name }}
        operator: {{ template "grafana-exporter.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-grafana-url={{ required ".Values.url is required" .Values.url }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: GRAFANA_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "grafana-exporter.fullname" . }}
                key: username
          - name: GRAFANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "grafana-exporter.fullname" . }}
                key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "grafana-exporter.fullname" . }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
