{{- if .Values.auth.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana-exporter.fullname" . }}
  labels:
    app: {{ template "grafana-exporter.name" . }}
    chart: {{ template "grafana-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    operator: {{ template "grafana-exporter.name" . }}
type: Opaque
data:
  username:  {{ required ".Values.auth.username is required" .Values.auth.username | b64enc }}
  password: {{ required ".Values.auth.password is required" .Values.auth.password | b64enc }}
{{- end }}
