{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "grafana-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    operator: {{ template "grafana-exporter.name" . }}
  name: {{ template "grafana-exporter.fullname" . }}
{{- end }}
